# Generated by Django 5.2.8 on 2026-10-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item_num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
